### ISSUE TITLE
Create (automagically) DNN961 fr-FR LP

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Language-Pack-FR-FR#11]
I assume the fr-FR pack is ready for DNN961?
So... shouldn't the LP release pack be (auto) created?

**Comment by valadas** [comment]
Unfortunatelly it is not ready yet, but I would love to have it ready for 9.6.1. Will try to find some more time to get back on this...

**Comment by valadas** [comment]
Well, I mean 9.6.2 actually.

**Comment by valadas** [comment]
Closing this as I am about to publish for 9.9.1
